name: Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t ducker556/ducker556:latest
      - name: publish
        run: |
          docker login -u ducker556 -p ${{ secrets.DOCKERHUB_TOKEN}}
          docker push ducker556/ducker556:latest
